### ISSUE TITLE
Please add "Version" or "Package-Version" header and tag a stable release > 1.4

### ISSUE THREAD

**Issue by sten0** [davep/mutt-alias.el#2]
Hi Dave,

Thank you for maintaining mutt-alias.el and for merging Debian's documentation earlier this summer.  Today I was surprised to find that mutt-alias.el still wasn't in Debian, so I reviewed the package again, and looked for what is missing.  First, I noticed that a "Version" or "Package-Version" header was missing https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html.  This isn't the end of the world, and I've worked around this by manually writing https://salsa.debian.org/emacsen-team/mutt-alias-el/blob/master/debian/mutt-alias-pkg.el.  Usually this information is autogenerated from the headers.  Nice to haves would also be keywords and a URL or Homepage field.

Second, please tag a stable release with the same version as `Version` or `Package-Version`, probably 1.4.1 or 1.5, as you like.  Right now I'm using `1.4+git20160523.f9b1c1e-1`, and both 1.4.1 and 1.5 will evaluate as greater than this.

Sincerely,
Nicholas

**Comment by davep** [comment]
Happy enough to do that, although it might be a short while before I'm in a position to.

I should also note that I've not used mutt, and so not used this code, in well over a decade. If there's still a use for this code it might be better maintained by someone who uses mutt.

**Comment by davep** [comment]
[v1.5](https://github.com/davep/mutt-alias.el/releases/tag/v1.5) now exists. Hopefully that'll be helpful. Please don't hesitate to let me know if you need anything else.
